import Head from "next/head";
import {
  useContractRead,
  useContractWrite,
  usePrepareContractWrite,
} from "wagmi";
import testABI from "@/abi/Test.json";
import bookABI from "@/abi/Book.json";
import { Web3Button, Web3NetworkSwitch } from "@web3modal/react";
import { BigNumber, ethers } from "ethers";
export default function Home() {
  const { config } = usePrepareContractWrite({
    address: testABI.address,
    abi: testABI.abi,
    chainId: 3141,
    functionName: "add",
    args: [],
  });

  const { write } = useContractWrite(config);

  const { data, isError, isLoading } = useContractRead({
    address: testABI.address,
    abi: testABI.abi,
    functionName: "integer",
  });

  console.log(data?.toString());
  return (
    <>
      <Head>
        <title>AUTHORize</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Web3Button />
        <button onClick={write}>add</button>
        {/* <p>{data}</p> */}
      </main>
    </>
  );
}
