import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>AUTHORize</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center p-10 space-y-20">
        <p>Page not created yet 🙁</p>
        <p>This page will allow peer to peer functionalities. Watch out!</p>
      </main>
    </>
  );
}
