import { UserContext } from "@/lib/context";
import { db } from "@/lib/firebase";
import { Web3Button } from "@web3modal/react";
import { doc, getDoc, setDoc } from "firebase/firestore";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useContext, useState } from "react";
import { useForm } from "react-hook-form";
import { useAccount } from "wagmi";

export default function SignIn() {
  const router = useRouter();
  const { address, isConnected } = useAccount();
  const { username } = useContext(UserContext);

  if (username) router.push("/users/me");

  const [randomPic, setRandomPic] = useState(parseInt(Math.random() * 1000000));

  const {
    handleSubmit,
    register,
    reset,
    formState: { errors },
  } = useForm();

  const signIn = async (values) => {
    const { username } = values;
    console.log(values);
    if (address && username) {
      try {
        const docRef = doc(db, "users", address);
        await setDoc(docRef, {
          username: username.toLowerCase(),
          userAvatar: randomPic,
          userETH: address,
        });
        router.push("/users/me");
      } catch (error) {
        console.log(error);
      }
    }
  };

  return (
    <>
      <Head>
        <title>AUTHORize</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center justify-center min-h-[calc(100vh-108px)]">
        <div class="w-1/3 relative bg-white rounded-lg shadow dark:bg-gray-700">
          <div class="relative px-6 py-6 lg:px-8">
            <h3 class="mb-4 text-xl font-medium text-gray-900 dark:text-white">
              Sign in to our platform
            </h3>
            <form className="space-y-6" onSubmit={handleSubmit(signIn)}>
              <div className="flex flex-col space-y-3">
                <p className="text-red-700 text-sm font-semibold">
                  Wallet Address*
                </p>
                <div className="p-3 rounded-lg bg-gray-50 w-full border-2 border-gray-500 overflow-x-hidden">
                  {address || "Connect Wallet Below 👇"}
                </div>
                <Web3Button />
              </div>

              <div>
                <p className="text-red-700 text-sm font-semibold">Username*</p>

                <input
                  placeholder="Pick a unique username"
                  className="p-3 rounded-lg bg-gray-50 w-full border-2 border-gray-500"
                  {...register("username")}
                />
              </div>

              <div>
                <p className="text-red-700 text-sm font-semibold">
                  {"Avatar (Click to change)*"}
                </p>
                <button
                  className="relative h-32 w-32"
                  onClick={() =>
                    setRandomPic(parseInt(Math.random() * 1000000))
                  }
                >
                  <Image
                    src={`https://avatars.dicebear.com/api/avataaars/${randomPic}.svg`}
                    fill={true}
                    className="rounded-full shadow-xl shadow-orange-500/50"
                  />
                </button>
              </div>
              <button
                className="absolute bottom-2 right-2 rounded-lg bg-orange-400 text-white p-2 hover:scale-105 font-semibold"
                type="submit"
              >
                Continue
              </button>
            </form>
          </div>
        </div>
      </main>
    </>
  );
}
