import { useUserData } from "@/lib/hooks";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useAccount } from "wagmi";
import { CiEdit } from "react-icons/ci";
import Link from "next/link";

export default function Dashboard() {
  const router = useRouter();
  const { id } = router.query;

  const { userAvatar, userETH, username, userAbout } = useUserData(id);
  const { address } = useAccount();

  return (
    <>
      <Head>
        <title>AUTHORize</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-row p-4 space-x-3">
        <section className="w-1/3 flex flex-col space-y-3">
          <div className=" border bg-white flex flex-col p-4 relative">
            <div className="mx-auto p-2 flex flex-col items-center space-y-1">
              <div className="w-36 h-36 overflow-hidden rounded-full mx-auto">
                <Image
                  src={`https://avatars.dicebear.com/api/avataaars/${userAvatar}.svg`}
                  width={144}
                  height={144}
                  className="rounded-full"
                  alt="Avatar"
                />
              </div>
              <p className="text-center font-semibold">{username}</p>
            </div>
            {userETH == address && (
              <Link
                className="absolute top-1 right-1 p-2 rounded-full hover:bg-gray-200"
                href={`/users/${id}/edit`}
              >
                <CiEdit size={20} />
              </Link>
            )}
          </div>

          <div className=" border bg-white flex flex-col p-4 relative">
            <p className="font-semibold text-sm text-left">About</p>
            <p className="font-light">{userAbout}</p>
          </div>
        </section>

        <section className="w-full flex flex-col space-y-3">
          <div className=" border bg-white flex flex-col p-4 relative h-[calc(100vh-128px)]">
            Owned Books
          </div>
          <div className=" border bg-white flex flex-col p-4 relative h-[calc(100vh-128px)]">
            Accessible Books
          </div>
        </section>
      </main>
    </>
  );
}
