import { useBooks, useUserData } from "@/lib/hooks";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useAccount, useContractRead } from "wagmi";
import { CiEdit } from "react-icons/ci";
import Link from "next/link";
import Book from "@/components/Book";
import keyABI from "@/abi/Key.json";
import { BsPlusCircle } from "react-icons/bs";

export default function Dashboard() {
  const router = useRouter();
  const { id } = router.query;

  const { userAvatar, userETH, username, userAbout } = useUserData(id);
  const { address } = useAccount();

  const ownedBooks = useBooks(["author", "==", username]);

  const {
    data: keyId,
    isError,
    isLoading,
  } = useContractRead({
    address: keyABI.address,
    abi: keyABI.abi,
    functionName: "getUserBooks",
    args: [address],
    onSettled(data, error) {
      console.log(data, error);
    },
  });

  return (
    <>
      <Head>
        <title>AUTHORize</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-row p-4 space-x-3">
        <section className="w-1/3 flex flex-col space-y-3">
          <div className=" border bg-white flex flex-col p-4 relative">
            <div className="mx-auto p-2 flex flex-col items-center space-y-1">
              <div className="w-36 h-36 overflow-hidden rounded-full mx-auto">
                <Image
                  src={`https://avatars.dicebear.com/api/avataaars/${userAvatar}.svg`}
                  width={144}
                  height={144}
                  className="rounded-full"
                  alt="Avatar"
                />
              </div>
              <p className="text-center font-semibold">{username}</p>
            </div>
            {userETH == address && (
              <Link
                className="absolute top-1 right-1 p-2 rounded-full hover:bg-gray-200"
                href={`/users/${id}/edit`}
              >
                <CiEdit size={20} />
              </Link>
            )}
          </div>

          <div className=" border bg-white flex flex-col p-4 relative">
            <p className="font-semibold text-sm text-left">About</p>
            <p className="font-light">{userAbout}</p>
          </div>
        </section>

        <section className="w-full flex flex-col space-y-3">
          <div className=" border bg-white flex flex-col p-4 relative h-[calc(100vh-128px)]">
            <p>Owned Books</p>
            <div className="flex p-2">
              {ownedBooks.map((obj, i) => (
                <Book details={obj} key={i} />
              ))}
              <Link
                href={"/books/new/edit"}
                className="inline-flex items-center justify-center p-2 border-2 border-orange-300 text-orange-300 h-60 w-40 hover:scale-105 hover:bg-orange-300 hover:text-white"
              >
                Create book <BsPlusCircle className="ml-2" size={20} />
              </Link>
            </div>
          </div>
          <div className=" border bg-white flex flex-col p-4 relative h-[calc(100vh-128px)]">
            <p>Accessible Books</p>
          </div>
        </section>
      </main>
    </>
  );
}
